version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  php:
    working_directory: ~/repo
    docker:
      - image: circleci/php:latest

jobs:
  build:
    executor: php
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.lock" }}
    - run: composer install --no-interaction --prefer-source --dev
    - save_cache:
        paths:
        - vendor
        key: v1-dependencies-{{ checksum "composer.lock" }}
    - run: composer cover
    - codecov/upload:
        file: ./coverage.xml
        flags: "unittests"
